print("=" * 50)
print("🐳 Welcome to My Dockerized Python Application")
print("=" * 50)
print()
print("👤 Developer: Tarun Agarwal")
print("📦 Containerized using Docker")
print("🚀 Built as part of my DevOps learning journey")
print()
print("✅ Skills demonstrated:")
print("   - Writing Dockerfiles")
print("   - Building Docker images")
print("   - Running containerized applications")
print("   - Pushing images to Docker Hub")
print()
print("=" * 50)
print("This container is running successfully! 🎉")
print("=" * 50)